<a href="https://colab.research.google.com/github/utper/Capstone/blob/master/conv_poll.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np

# Definir una imagen de ejemplo (5x5)
# Imagen con un borde vertical en la columna central
imagen = np.array([
    [1, 1, 10, 10, 10],
    [1, 1, 10, 10, 10],
    [1, 1, 10, 10, 10],
    [1, 1, 10, 10, 10],
    [1, 1, 10, 10, 10]
])

# Definir un kernel de convolución (3x3)
# Filtro de detección de bordes verticales
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# Dimensiones de la imagen y el kernel
filas, columnas = imagen.shape
k_filas, k_columnas = kernel.shape

# Crear la salida de convolución
# inicializa con ceros
conv_output = np.zeros((filas - k_filas + 1, columnas - k_columnas + 1))
print(conv_output)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [38]:

# Aplicar la convolución con un for
# conv_output[0, 0] = 1*1 + 1*0 + 10*(-1) +
#                     1*1 + 1*0 + 10*(-1) +
#                     1*1 + 1*0 + 10*(-1)
# conv_output[0, 0] = -27

# conv_output[0, 1] = 1*1 + 10*0 + 10*(-1) +
#                     1*1 + 10*0 + 10*(-1) +
#                     1*1 + 10*0 + 10*(-1)
# conv_output[0, 1] = -27

# conv_output[0, 2] = 10*1 + 10*0 + 10*(-1) +
#                     10*1 + 10*0 + 10*(-1) +
#                     10*1 + 10*0 + 10*(-1)
# conv_output[0, 2] = 0

for i in range(conv_output.shape[0]):
    for j in range(conv_output.shape[1]):
        conv_output[i, j] = np.sum(imagen[i:i+k_filas, j:j+k_columnas] * kernel)

print("Resultado de la convolución:")
print(conv_output)


Resultado de la convolución:
[[-27. -27.   0.]
 [-27. -27.   0.]
 [-27. -27.   0.]]


In [40]:
# conv_output.shape[0] es la cantidad de filas en la matriz de la convolución.
# conv_output.shape[1] es la cantidad de columnas en la matriz de la convolución.
# pool_size es el tamaño del bloque de pooling (por ejemplo, 2 para max pooling de 2x2).
pool_size = 2

# Asegurar que las dimensiones sean múltiplos de pool_size
# Ajustar el tamaño de la salida del pooling asegurando que encaje bien
# * conv_output.shape[0] // pool_size y conv_output.shape[1] // pool_size , son diviones enteras con redondeo hacia abajo, por
#   lo tanto: pool_output_shape = (1,1)
pool_output_shape = (conv_output.shape[0] // pool_size, conv_output.shape[1] // pool_size)
pool_output = np.zeros(pool_output_shape)

# Aplicar max pooling con verificación de límites
# range(start, stop, step)
for i in range(0, pool_output_shape[0] * pool_size, pool_size):  # range(0, 2, 2)
    for j in range(0, pool_output_shape[1] * pool_size, pool_size): # range(0, 2, 2)
        # recordemos que tomara bloques 2x2, por ejemplo:
        # Primer bloque:
        # max = -27
        # [-27. -27.]
        # [-27. -27.]
        # Segundo bloque (pero este bloque quedó fuera debido a los límites del pooling en este caso):
        # max = 0
        # [-27. 0.]
        # [-27. 0.]
        pool_output[i//pool_size, j//pool_size] = np.max(conv_output[i:i+pool_size, j:j+pool_size])

print("\nResultado del max pooling:")
print(pool_output)


Resultado del max pooling:
[[-27.]]
